wandb_version: 1

SGD_momentum:
  desc: null
  value: 0.6566222749612993
_wandb:
  desc: null
  value:
    cli_version: 0.12.17
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1657373039
    t:
      1:
      - 1
      - 5
      - 41
      - 51
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 51
      - 53
      - 55
      3:
      - 16
      4: 3.9.13
      5: 0.12.17
      8:
      - 5
arteries_pred_loss_ratio:
  desc: null
  value: 0.2071422613609661
balance_method:
  desc: null
  value: undersample
batch_norm_patient:
  desc: null
  value: false
batch_size:
  desc: null
  value: 4
change_strategy_epoch_l:
  desc: null
  value:
  - -1
criterion_l:
  desc: null
  value:
  - BCE
dataset_type:
  desc: null
  value: transformer_patient
dropout:
  desc: null
  value: 0.014775322741393282
dropout_patient_net:
  desc: null
  value: 0.0700010465677528
gaussian_blur:
  desc: null
  value: null
load_network:
  desc: null
  value: null
lr_l:
  desc: null
  value:
  - 0.0004493489445028419
n_epochs:
  desc: null
  value: 2
nb_cv:
  desc: null
  value: null
nb_neur_per_hidden_layer_patient:
  desc: null
  value:
  - 50
  - 10
nb_patch_l:
  desc: null
  value:
  - 32
  - 64
  - 128
  - 128
network_class:
  desc: null
  value: transfo_and_pat_softmax_net.PatientLevelDNN_PatientDataSoftmax
normalise:
  desc: null
  value: false
normalise_patient:
  desc: null
  value: true
optimizer_l:
  desc: null
  value:
  - SGD
patch_randomness:
  desc: null
  value: 0.1
patch_size_l:
  desc: null
  value:
  - 64
  - 64
  - 64
  - 64
patient_data_loss_ratio:
  desc: null
  value: 0.09457471894183037
random_crop:
  desc: null
  value: 0.1
random_rotation:
  desc: null
  value: 0.1
save_best_net:
  desc: null
  value: true
scheduler_factor:
  desc: null
  value: 0.1
scheduler_patience:
  desc: null
  value: 5
seed:
  desc: null
  value: 42
siamese_pred_loss_ratio:
  desc: null
  value: 7.399590987258929e-05
test:
  desc: null
  value: false
train_test_ratio:
  desc: null
  value: 0.2
weight_decay:
  desc: null
  value: 0.00634788540665404
weights_init:
  desc: null
  value: Xavier Uniform
weights_init_patient:
  desc: null
  value: Kaiming Uniform
